### ISSUE TITLE
Segmentation fault occurs after  UplinkPacketOut

### ISSUE THREAD

**Issue by siddiqui-io** [opencord/voltha-bbsim#1]
**The way I ran it:**
docker run -it --rm --privileged=true --expose=50060 --network=compose_default voltha/voltha-bbsim /go/src/gerrit.opencord.org/voltha-bbsim/bbsim -n 4

**Preprovisioned and enabled the device using voltha-cli**

**Error:**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8340d2]

goroutine 25 [running]:
gerrit.opencord.org/voltha-bbsim/core.getDot1QLayer(0x0, 0x0, 0x0)
        /go/src/gerrit.opencord.org/voltha-bbsim/core/io_worker.go:121 +0x22
gerrit.opencord.org/voltha-bbsim/core.PopVLAN(0x0, 0x0, 0x0, 0x0, 0xc420070000, 0xe7b740, 0xc42003bcc0)
        /go/src/gerrit.opencord.org/voltha-bbsim/core/io_worker.go:54 +0x4d
gerrit.opencord.org/voltha-bbsim/core.(*Server).uplinkPacketOut(0xc4200502a0, 0xe89e40, 0xc420079a20, 0xe7dd80, 0xc420019418)
        /go/src/gerrit.opencord.org/voltha-bbsim/core/core_server.go:349 +0xa4
gerrit.opencord.org/voltha-bbsim/core.(*Server).UplinkPacketOut(0xc4200502a0, 0xe84980, 0xc4201c8630, 0xc42004dc40, 0xc4200502a0, 0xe84980, 0xc4201c85a0)
        /go/src/gerrit.opencord.org/voltha-bbsim/core/grpc_service.go:98 +0x167
gerrit.opencord.org/voltha-bbsim/protos._Openolt_UplinkPacketOut_Handler(0x961980, 0xc4200502a0, 0xe84980, 0xc4201c8630, 0xc4201bccd0, 0x0, 0x0, 0x0, 0xc420014ea0, 0x5e)
        /go/src/gerrit.opencord.org/voltha-bbsim/protos/openolt.pb.go:3633 +0x279
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420001680, 0xe89640, 0xc4201ac000, 0xc4201b6a00, 0xc42018e1b0, 0xe73d28, 0x0, 0x0, 0x0)
        /go/src/google.golang.org/grpc/server.go:935 +0x464
google.golang.org/grpc.(*Server).handleStream(0xc420001680, 0xe89640, 0xc4201ac000, 0xc4201b6a00, 0x0)
        /go/src/google.golang.org/grpc/server.go:1161 +0x1528
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420018660, 0xc420001680, 0xe89640, 0xc4201ac000, 0xc4201b6a00)
        /go/src/google.golang.org/grpc/server.go:683 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/google.golang.org/grpc/server.go:681 +0xa1

**Comment by k-nishimoto** [comment]
I really thank you for your report.
I fixed the BUG you reported at a commit "VOL-1119 BBSim - DHCP emulation".

I'm very glad if you git-clone the latest version, and try it again.
